apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  selector:
    matchLabels:
      run: client
  replicas: 2
  template:
    metadata:
      labels:
        run: client
    spec:
      containers:
      - name: client
        image: cenwadike/dockerhub:mern-client
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata: 
  name: client-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30001
  selector:
    run: client
  type: LoadBalancer