version: '3.8'

services:
  server:
    image: server
    build: ../MERN-CRUD/server
    ports:
      - "8080:8080"
    working_dir: /server
    command: npm run start

  # client:
  #   image: client
  #   build: ../MERN-CRUD/client
  #   ports:
  #     - "3000:3000"
  #   working_dir: /MERN-CRUD/client
  #   command: npm start