version: '3.8'

services:
  server:
    image: server
    build: ../server
    ports:
      - "8080:8080"
    volumes:
      - .:/server
    working_dir: /server
    command: npm run start

  client:
    image: client
    build: ../client
    ports:
      - "3000:3000"
    volumes:
      - .:/client
    working_dir: /client
    command: npm start