apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config-map
data:
  database-url: mongo-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  selector:
    matchLabels:
      run: server
  replicas: 2
  template:
    metadata:
      labels:
        run: server
    spec:
      containers:
      - name: server
        image: cenwadike/dockerhub:mern-server
        ports:
        - containerPort: 8081
        env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: server-config-map
              key: database-url
              
---

apiVersion: v1
kind: Service
metadata: 
  name: server-service
spec:
  ports:
  - port: 8081
    protocol: TCP
    nodePort: 30003
  selector:
    run: server
  type: LoadBalancer